version: "3.8"

volumes:
    prometheus_data: {}
    grafana_data: {}


services:
  prometheus:
    labels:
      demo: "monitoring"
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - target: 9090
        published: 9090
        protocol: tcp
        mode: host

  grafana:
    labels:
      demo: "monitoring"
    image: grafana/grafana:7.1.3
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
